local quotes = {
  '‘according to me’ is the only ‘according to’ that matters',
  'a diamond is a chunk of coal that did well under pressure',
  'a flower that smells the sweetest is shy and lowly',
  'at the touch of love everyone becomes a poet',
  'behind every great man is a woman rolling her eyes',
  'believe in yourself',
  'be young. be dope. be proud',
  'cry a river. build a bridge. get over it',
  'don’t stop until you are proud',
  'dream big. work hard',
  'either you run the day or the day runs you',
  'god has no religion',
  'happiness is by choice not by chance',
  'how to be successful? focus on your shit',
  'if you can’t handle the stress, you won’t manage success',
  'i’m a good person with a bad attitude',
  'i’m not lazy i’m just on my energy saving mode',
  'keep dreaming. stay busy. be happy',
  'no reason to stay is a good reason to go',
  'shhhh… i’m hiding from stupid people',
  'some people just want to watch the world burn',
  'stop thinking and just let things happen',
  'success is the best revenge. bullshit, revenge is the best revenge',
  'the brave men did not kill dragons. the brave men rode them',
  'the eyes are useless when the mind is blind',
  'the root of suffering is attachment',
  'the trouble is you think you have time',
  'think i’m sarcastic? watch me pretend to care',
  'when you choose to forgive those who have hurt you, you take away their power',
  'win a no win situation by rewriting the rules',
  'people say nothing is impossible, but i do nothing every day',
  'a bank is a place that will lend you money if you can prove that you don’t need it',
  'a black cat crossing your path signifies that the animal is going somewhere',
  'a clear conscience is usually the sign of a bad memory',
  'a committee is a group that keeps minutes and loses hours',
  'a computer once beat me at chess, but it was no match for me at kick boxing',
  'a day without laughter is a day wasted',
  'a great pleasure in life is doing what people say you cannot do',
  'a lie gets halfway around the world before the truth has a chance to get its pants on',
  'a man doesn’t know what he knows until he knows what he doesn’t know',
  'a pessimist is a person who has had to listen to too many optimists',
  'a rich man is nothing but a poor man with money',
  'a verbal contract isn’t worth the paper it’s written on',
  'a woman’s mind is cleaner than a man’s: she changes it more often',
  'age is an issue of mind over matter. if you don’t mind, it doesn’t matter',
  'all men are equal before fish',
  'all the things i really like to do are either immoral, illegal or fattening',
  'always borrow money from a pessimist. he won’t expect it back',
  'always forgive your enemies – nothing annoys them so much',
  'always remember that you are absolutely unique. just like everyone else',
  'an alcoholic is someone you don’t like who drinks as much as you do',
  'as a child my family’s menu consisted of two choices: take it or leave it',
  'as long as people will accept crap, it will be financially profitable to dispense it',
  'ask me no questions, and i’ll tell you no lies',
  'avoid fruits and nuts. you are what you eat',
  'be careful about reading health books. you may die of a misprint',
  'behind every successful man is a woman, behind her is his wife',
  'better to remain silent and be thought a fool than to speak out and remove all doubt',
  'biologically speaking, if something bites you it’s more likely to be female',
  'cleaning up with children around is like shoveling during a blizzard',
  'clothes make the man. naked people have little or no influence on society',
  'do not take life too seriously. you will never get out of it alive',
  'don’t cry because it’s over. smile because it happened',
  'education is learning what you didn’t even know you didn’t know',
  'every man is guilty of all the good he did not do',
  'everybody laughs the same in every language because laughter is a universal connection',
  'everyone has a purpose in life. perhaps yours is watching television',
  'everything that used to be a sin is now a disease',
  'flattery is like cologne, to be smelt, not swallowed',
  'folks, i don’t trust children. they’re here to replace us',
  'forgive your enemies, but never forget their names',
  'give me a woman who loves beer and i will conquer the world',
  'god is at home, it’s we who have gone out for a walk',
  'good advice is something a man gives when he is too old to set a bad example',
  'happiness is having a large, loving, caring, close-knit family in another city',
  'have no fear of perfection. you’ll never reach it',
  'have you noticed that all the people in favor of birth control are already born?',
  'he who laughs last didn’t get the joke',
  'health nuts are going to feel stupid someday, lying in hospitals dying of nothing',
  'here’s to our wives and girlfriends…may they never meet!',
  'high heels were invented by a woman who had been kissed on the forehead',
  'how many people here have telekenetic powers? raise my hand',
  'i always arrive late at the office, but i make up for it by leaving early',
  'i always wanted to be somebody, but now i realize i should have been more specific',
  'i am an old man and have known a great many troubles, but most of them never happened',
  'i am only human, although i regret it',
  'i am so clever that sometimes i don’t understand a single word of what i am saying',
  'i can resist everything except temptation',
  'i don’t believe in astrology; i’m a sagittarius and we’re skeptical',
  'i don’t think anyone should write their autobiography until after they’re dead',
  'i drink to make other people more interesting',
  'i found there was only one way to look thin: hang out with fat people',
  'i hate women because they always know where things are',
  'i have learned from my mistakes, and i am sure i can repeat them exactly',
  'i have not failed. i’ve just found 10,000 ways that won’t work',
  'i intend to live forever. so far, so good',
  'i live by my own rules (reviewed, revised, and approved by my wife).. but still my own',
  'i refuse to answer that question on the grounds that i don’t know the answer',
  'i refuse to join any club that would have me as a member',
  'i used to jog but the ice cubes kept falling out of my glass',
  'i was born to make mistakes, not to fake perfection',
  'i was married by a judge. i should have asked for a jury',
  'i wish i were dumber so i could be more certain about my opinions. it looks fun',
  'i would have written a shorter letter, but i did not have the time',
  'if i were two-faced, would i be wearing this one?',
  'if any of you cry at my funeral i’ll never speak to you again',
  'if evolution really works, how come mothers only have two hands?',
  'if life was fair, elvis would be alive and all the impersonators would be dead',
  'if you can’t live without me, why aren’t you dead already?',
  'if you come to a fork in the road, take it',
  'if you find it hard to laugh at yourself, i would be happy to do it for you',
  'if you have a secret, people will sit a little bit closer',
  'if you live to be one hundred, you’ve got it made. very few people die past that age',
  'if you love something set it free, but don’t be surprised if it comes back with herpes',
  'if you must make a noise, make it quietly',
  'if you think nobody cares if you’re alive, try missing a couple of car payments',
  'if you think you are too small to make a difference, try sleeping with a mosquito',
  'if you try to fail, and succeed, which have you done?',
  'if you want your children to listen, try talking softly to someone else',
  'if you’re going through hell, keep going',
  'if you’re going to tell people the truth, be funny or they’ll kill you',
  'if you’re too open-minded; your brains will fall out',
  'it does not matter whether you win or lose, what matters is whether i win or lose!',
  'it takes considerable knowledge just to realize the extent of your own ignorance',
  'it’s just a job. grass grows, birds fly, waves pound the sand. i beat people up',
  'it’s true hard work never killed anybody, but i figure, why take the chance?',
  'i’d rather have 1% of the effort of 100 men than 100% of my own effort',
  'i’m not for everyone. i’m barely for me',
  'i’m such a good lover because i practice a lot on my own',
  'i’ve got all the money i’ll ever need, if i die by four o’clock',
  'knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad',
  'laugh a lot. it burns a lot of calories',
  'lead me not into temptation; i can find the way myself',
  'leave something for someone but dont leave someone for something',
  'life is a sexually transmitted disease',
  'life is hard. after all, it kills you',
  'life is hard; it’s harder if you’re stupid',
  'love is an irresistible desire to be irresistibly desired',
  'man has his will, but woman has her way',
  'marriage is like mushrooms: we notice too late if they are good or bad',
  'marriage is the chief cause of divorce',
  'marriage is the only war in which you sleep with the enemy',
  'may the forces of evil become confused on the way to your house',
  'money is not the most important thing in the world. love is. fortunately, i love money',
  'most people would sooner die than think; in fact, they do so',
  'my favorite machine at the gym is the vending machine',
  'my opinions may have changed, but not the fact that i’m right',
  'my pessimism extends to the point of even suspecting the sincerity of other pessimists',
  'my theory is that all of scottish cuisine is based on a dare',
  'never go to a doctor whose office plants have died',
  'never have more children than you have car windows',
  'never put off till tomorrow what you can do the day after tomorrow',
  'never under any circumstances take a sleeping pill and a laxative on the same night',
  'nobody realizes that some people expend tremendous energy merely to be normal',
  'of all the things i’ve lost i miss my mind the most',
  'older people shouldn’t eat health food, they need all the preservatives they can get',
  'one tequila, two tequila, three tequila, floor',
  'people who think they know everything are a great annoyance to those of us who do',
  'political correctness is tyranny with manners',
  'recession is when a neighbor loses his job. depression is when you lose yours',
  'remember, today is the tomorrow you worried about yesterday',
  'roses are red, violets are blue, i’m schizophrenic, and so am i',
  'the average dog is a nicer person than the average person',
  'the avoidance of taxes is the only intellectual pursuit that still carries any reward',
  'the best thing about the future is that it comes one day at a time',
  'the cure for boredom is curiosity. there is no cure for curiosity',
  'the difference between stupidity and genius is that genius has its limits',
  'the digital camera is a great invention because it allows us to reminisce. instantly',
  'the duty of a patriot is to protect his country from its government',
  'the early bird gets the worm, but the second mouse gets the cheese',
  'the first time i sang in the church choir; two hundred people changed their religion',
  'the man who smiles when things go wrong has thought of someone to blame it on',
  'the only mystery in life is why the kamikaze pilots wore helmets',
  'the only reason some people get lost in thought is because it’s unfamiliar territory',
  'the only time a woman really succeeds in changing a man is when he is a baby',
  'the road to success is always under construction',
  'the road to success is dotted with many tempting parking spaces',
  'the safe way to double your money is to fold it over once and put it in your pocket',
  'the two most common elements in the universe are hydrogen and stupidity',
  'the world is a globe. the farther you sail, the closer to home you are',
  'the world is full of magical things patiently waiting for our wits to grow sharper',
  'there’s a fine line between genius and insanity. i have erased this line',
  'to be sure of hitting the target, shoot first, and call whatever you hit the target',
  'to err is human, but to really foul things up you need a computer',
  'to err is human; to admit it, superhuman',
  'to steal ideas from one person is plagiarism; to steal from many is research',
  'trouble knocked at the door, but, hearing laughter, hurried away',
  'war is god’s way of teaching americans geography',
  'we learn from experience that men never learn anything from experience',
  'we never really grow up, we only learn how to act in public',
  'what the world needs is more geniuses with humility; there are so few of us left',
  'when a man opens a car door for his wife, it’s either a new car or a new wife',
  'when we remember we are all mad, the mysteries disappear and life stands explained',
  'when we talk to god, we’re praying. when god talks to us, we’re schizophrenic',
  'when you’re in love it’s the most glorious two and a half days of your life',
  'whoever said money can’t buy happiness didn’t know where to shop',
  'why do they call it rush hour when nothing moves?',
  'why is there so much month left at the end of the money?',
  'wine is constant proof that god loves us and loves to see us happy',
  'women are meant to be loved, not to be understood',
  'women are wiser than men because they know less and understand more',
  'worrying is like paying a debt you don’t owe',
  'you cannot be anything if you want to be everything',
  'you can’t have everything. where would you put it?',
  'you tried your best and you failed miserably. the lesson is ‘never try',
  'you’re only as good as your last haircut',
}

local function break_text(text, width)
  -- handle base cases
  if text == nil or width == nil or width <= 0 then
    error("bad args")
  elseif #text <= width then
      return { text }
  end

  -- break text into lines
  local lines = {}
  local line = ''

  for word in string.gmatch(text, '%S+') do
    if line ~= ''  and #line + #word + 1 > width then
      table.insert(lines, line)
      line = word
    else
      if #line > 0 then
        line = line .. ' ' .. word
      else
        line = word
      end
    end
  end

  table.insert(lines, line)
  return lines
end

local function get_random_quote()
  math.randomseed(os.time())
  return quotes[math.random(#quotes)]
end

return {
  break_text = break_text,
  get_random_quote = get_random_quote,
}
