
format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$nodejs\
$elixir\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[->](bold bright-green)"
error_symbol = "[->](bold bright-red)"

[directory]
style = "bold bright-purple"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = true

[hostname]
format = "on [$hostname](cyan) "

[git_branch]
style = "bold bright-red"

[git_commit]
style = "bright-green"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✘${count}"
renamed = "»${count}"
style = "blue"

[cmd_duration]
style = "bright-cyan"

[docker_context]
style = "cyan"

[python]
style = "yellow"

[nodejs]
style = "bright-green"

[elixir]
style = "bright-purple"

