add_newline = true

scan_timeout = 10

[character]
success_symbol = "[➜](bold bright-green)"
error_symbol = "[➜](bold bright-red)"

[directory]
style = "bold bright-yellow"
read_only = " 🔒"

[hostname]
ssh_only = true
format =  "on [$hostname](bright-red) "

[git_branch]
style = "bold bright-purple"

[git_commit]
style = "bright-green"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bright-red"

[cmd_duration]
style = "bright-cyan"

[aws]
style = "202"
disabled = true

[docker_context]
style = "39"

[python]
style = "yellow"

[nodejs]
style = "bright-green"

[php]
style = "147"

[package]
disabled = true

[battery]
disabled = true
