add_newline = true

scan_timeout = 10

palette = "custom"

[character]
success_symbol = "[➜](bold bright-green)"
error_symbol = "[➜](bold bright-red)"

[directory]
style = "bold bright-purple"
read_only = " 🔒"

[hostname]
ssh_only = true
format =  "on [$hostname](cyan) "

[git_branch]
style = "bold pink"

[git_commit]
style = "bright-green"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "blue"

[cmd_duration]
style = "bright-cyan"

[aws]
style = "202"
disabled = true

[docker_context]
style = "39"

[python]
style = "orange"

[nodejs]
style = "bright-green"

[php]
style = "147"

[package]
disabled = true

[battery]
disabled = true

[palettes.custom]
orange = "#ff7400"
pink = "#ff5b77"
