add_newline = true

scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
style = "123"
read_only = " 🔒"

[hostname]
ssh_only = true
format =  "on [$hostname](red) "

[git_branch]
style = "214"

[git_commit]
style = "green"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "red"

[cmd_duration]
style = "purple"

[aws]
style = "202"
disabled = true

[docker_context]
style = "39"

[python]
style = "yellow"

[nodejs]
style = "green"

[php]
style = "147"

[package]
disabled = true

[battery]
disabled = true
