return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = { 'BufReadPre', 'BufNewFile' },
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = {
        'bash',
        'fish',
        'html',
        'xml',
        'css',
        'scss',
        'lua',
        'luadoc',
        'markdown',
        'yaml',
        'toml',
        'vim',
        'vimdoc',
        'python',
        'javascript',
        'typescript',
        'dockerfile',
        'elixir',
        'vue',
        'regex',
        'sql',
        'csv',
      },
      auto_install = true,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
