[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors.bright]
black = "0x2E3436"
blue = "0x0076DE"
cyan = "0x4DFFFF"
green = "0x82C237"
magenta = "0xAA7CF3"
red = "0xF22A70"
white = "0xF7F7F7"
yellow = "0xFFAC00"

[colors.normal]
black = "0x6E706B"
blue = "0x98D4FF"
cyan = "0x89FFFF"
green = "0xABC191"
magenta = "0xFFB2FF"
red = "0xEE7757"
white = "0xD3D7CF"
yellow = "0xFBDF3A"

[colors.primary]
background = "0x2E3436"
foreground = "0xF7F7F7"

[cursor]
style = "Beam"

[font]
size = 8

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 3
y = 0
