[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors.bright]
black = "#2E3436"
blue = "#0076DE"
cyan = "#4DFFFF"
green = "#82C237"
magenta = "#AA7CF3"
red = "#F4005F"
white = "#F7F7F7"
yellow = "#FFAC00"

[colors.normal]
black = "#6E706B"
blue = "#98D4FF"
cyan = "#89FFFF"
green = "#ABC191"
magenta = "#FFB2FF"
red = "#EE7757"
white = "#D3D7CF"
yellow = "#FBDF3A"

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#7F849C"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.selection]
text = "#2E3436"
background = "#D8EAFA"

[cursor]
style = "Beam"

[font]
size = 8

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 3
y = 0
